### ISSUE TITLE
how to use it to training a chatbot?

### ISSUE THREAD

**Issue by SeekPoint** [musyoku/chainer-qrnn#1]
suppose I got two files, 
one contains Questions for each line , 
one contains Answer for each line corresondingly,
in both of them, all the words divide by blank

**Comment by SeekPoint** [comment]
I had it run by delete all the dev_set & test_set code, but not sure it is making sense

**Comment by musyoku** [comment]
To train without dev_set and test_set, just run as follows:
`python train.py --source-train questions.txt --target-train answers.txt`

**Comment by SeekPoint** [comment]
mldl@mldlUB1604:~/ub16_prj/chainer-qrnn-update/seq2seq$ python train.py --source-train ../../../_train.q --target-train ../../../_train.a
1---the file None doesn't exist
1---the file None doesn't exist
1---the file None doesn't exist
1---the file None doesn't exist
1---len(source_dataset_train) is 14277778 
1---len(target_dataset_train) is 14277778
Traceback (most recent call last):
  File "train.py", line 233, in <module>
    main(args)
  File "train.py", line 62, in main
    source_buckets_train, target_buckets_train = make_buckets(source_dataset_train, target_dataset_train)
  File "/home/mldl/ub16_prj/chainer-qrnn-update/seq2seq/dataset.py", line 154, in make_buckets
    word_ids_source.insert(0, ID_PAD)	# prepend
AttributeError: 'str' object has no attribute 'insert'

**Comment by SeekPoint** [comment]
after I convert it to the list:

another error raised:

mldl@mldlUB1604:~/ub16_prj/chainer-qrnn-update/seq2seq$ python3 train.py --source-train ../../../_train.q --target-train ../../../_train.a
Traceback (most recent call last):
  File "train.py", line 233, in <module>
    main(args)
  File "train.py", line 62, in main
    source_buckets_train, target_buckets_train = make_buckets(source_dataset_train, target_dataset_train)
  File "/home/mldl/ub16_prj/chainer-qrnn-update/seq2seq/dataset.py", line 170, in make_buckets
    buckets_source.append(np.asarray(bucket_source).astype(np.int32))
ValueError: invalid literal for int() with base 10: 't'

**Comment by musyoku** [comment]
The file path (`../../../_train.q` & `../../../_train.a`) may be incorrect.

**Comment by SeekPoint** [comment]
No， I checked

**Comment by musyoku** [comment]
Is the character code of `_train.a` & `_train.q` UTF-8?

**Comment by SeekPoint** [comment]
yes

**Comment by musyoku** [comment]
What do these lines mean?
```
1---the file None doesn't exist
1---the file None doesn't exist
1---the file None doesn't exist
1---the file None doesn't exist
1---len(source_dataset_train) is 14277778
1---len(target_dataset_train) is 14277778
```

**Comment by musyoku** [comment]
I updated the code so please try again.

**Comment by SeekPoint** [comment]
mldl@mldlUB1604:~/ub16_prj/chainer-qrnn-update/seq2seq$ python train.py --source-train ../../../_train.q --target-train ../../../_train.a





len of source dataset is 14277778
len of target dataset is 14277778
data	#
train	14277778
vocab	12192	(source)
vocab	19429	(target)
buckets 	#data	(train)
(5, 10) 	1554713
(10, 15) 	2343029
(20, 25) 	4561161
(40, 50) 	3083714
(100, 110) 	1458338
(200, 210) 	1272449
Epoch 1
Traceback (most recent call last):
  File "train.py", line 233, in <module>
    main(args)
  File "train.py", line 151, in main
    last_hidden_states = model.encode(source_batch, skip_mask)
  File "/home/mldl/ub16_prj/chainer-qrnn-update/seq2seq/model.py", line 164, in encode
    enmbedding = self.encoder_embed(X)
  File "/usr/local/lib/python2.7/dist-packages/chainer/links/connection/embed_id.py", line 53, in __call__
    return embed_id.embed_id(x, self.W, ignore_label=self.ignore_label)
  File "/usr/local/lib/python2.7/dist-packages/chainer/functions/connection/embed_id.py", line 111, in embed_id
    return EmbedIDFunction(ignore_label=ignore_label)(x, W)
  File "/usr/local/lib/python2.7/dist-packages/chainer/function.py", line 200, in __call__
    outputs = self.forward(in_data)
  File "/usr/local/lib/python2.7/dist-packages/chainer/functions/connection/embed_id.py", line 45, in forward
    mask = (x == self.ignore_label)
  File "cupy/core/core.pyx", line 911, in cupy.core.core.ndarray.__richcmp__ (cupy/core/core.cpp:20120)
  File "cupy/core/elementwise.pxi", line 776, in cupy.core.core.ufunc.__call__ (cupy/core/core.cpp:48462)
  File "cupy/util.pyx", line 39, in cupy.util.memoize.decorator.ret (cupy/util.cpp:1480)
  File "cupy/core/elementwise.pxi", line 584, in cupy.core.core._get_ufunc_kernel (cupy/core/core.cpp:44932)
  File "cupy/core/elementwise.pxi", line 32, in cupy.core.core._get_simple_elementwise_kernel (cupy/core/core.cpp:34609)
  File "cupy/core/carray.pxi", line 87, in cupy.core.core.compile_with_cache (cupy/core/core.cpp:34264)
  File "/usr/local/lib/python2.7/dist-packages/cupy/cuda/compiler.py", line 125, in compile_with_cache
    env = (arch, options, _get_nvcc_version())
  File "/usr/local/lib/python2.7/dist-packages/cupy/cuda/compiler.py", line 22, in _get_nvcc_version
    _nvcc_version = _run_nvcc(cmd, '.')
  File "/usr/local/lib/python2.7/dist-packages/cupy/cuda/compiler.py", line 61, in _run_nvcc
    raise OSError(msg)
OSError: Failed to run `nvcc` command. Check PATH environment variable: [Errno 12] Cannot allocate memory
mldl@mldlUB1604:~/ub16_prj/chainer-qrnn-update/seq2seq$

**Comment by musyoku** [comment]
What is the minibatch size?
If it fails with a memory error, the minibatch size may be too large.

**Comment by musyoku** [comment]
batchsize seems to be the default (64).
Try small values such as 32 or 16.

```
python train.py --source-train ../../../_train.q --target-train ../../../_train.a -b 16
```

**Comment by SeekPoint** [comment]
mldl@mldlUB1604:~/ub16_prj/chainer-qrnn-update/seq2seq$ python train.py --source-train ../../../_train.q --target-train ../../../_train.a -b 4
len of source dataset is 14277778
len of target dataset is 14277778
data	#
train	14277778
vocab	12192	(source)
vocab	19429	(target)
buckets 	#data	(train)
(5, 10) 	1554713
(10, 15) 	2343029
(20, 25) 	4561161
(40, 50) 	3083714
(100, 110) 	1458338
(200, 210) 	1272449
Epoch 1
Traceback (most recent call last):
  File "train.py", line 233, in <module>
    main(args)
  File "train.py", line 151, in main
    last_hidden_states = model.encode(source_batch, skip_mask)
  File "/home/mldl/ub16_prj/chainer-qrnn-update/seq2seq/model.py", line 164, in encode
    enmbedding = self.encoder_embed(X)
  File "/usr/local/lib/python2.7/dist-packages/chainer/links/connection/embed_id.py", line 53, in __call__
    return embed_id.embed_id(x, self.W, ignore_label=self.ignore_label)
  File "/usr/local/lib/python2.7/dist-packages/chainer/functions/connection/embed_id.py", line 111, in embed_id
    return EmbedIDFunction(ignore_label=ignore_label)(x, W)
  File "/usr/local/lib/python2.7/dist-packages/chainer/function.py", line 200, in __call__
    outputs = self.forward(in_data)
  File "/usr/local/lib/python2.7/dist-packages/chainer/functions/connection/embed_id.py", line 45, in forward
    mask = (x == self.ignore_label)
  File "cupy/core/core.pyx", line 911, in cupy.core.core.ndarray.__richcmp__ (cupy/core/core.cpp:20120)
  File "cupy/core/elementwise.pxi", line 776, in cupy.core.core.ufunc.__call__ (cupy/core/core.cpp:48462)
  File "cupy/util.pyx", line 39, in cupy.util.memoize.decorator.ret (cupy/util.cpp:1480)
  File "cupy/core/elementwise.pxi", line 584, in cupy.core.core._get_ufunc_kernel (cupy/core/core.cpp:44932)
  File "cupy/core/elementwise.pxi", line 32, in cupy.core.core._get_simple_elementwise_kernel (cupy/core/core.cpp:34609)
  File "cupy/core/carray.pxi", line 87, in cupy.core.core.compile_with_cache (cupy/core/core.cpp:34264)
  File "/usr/local/lib/python2.7/dist-packages/cupy/cuda/compiler.py", line 125, in compile_with_cache
    env = (arch, options, _get_nvcc_version())
  File "/usr/local/lib/python2.7/dist-packages/cupy/cuda/compiler.py", line 22, in _get_nvcc_version
    _nvcc_version = _run_nvcc(cmd, '.')
  File "/usr/local/lib/python2.7/dist-packages/cupy/cuda/compiler.py", line 61, in _run_nvcc
    raise OSError(msg)
OSError: Failed to run `nvcc` command. Check PATH environment variable: [Errno 12] Cannot allocate memory

**Comment by musyoku** [comment]
Try:
```
python train.py --source-train ../../../_train.q --target-train ../../../_train.a -b 1 --buckets-slice 0
```

**Comment by musyoku** [comment]
I think long sequence data exceeds the GPU memory capacity.

**Comment by SeekPoint** [comment]
_train.q and _train.a are both line by line format, all lines is 10 millions 
one line is one sentence for question or anwser

**Comment by musyoku** [comment]
The longer the sentence, the larger the required memory size.

**Comment by SeekPoint** [comment]
I think the longest sentence should not more than 100 characters
