### ISSUE TITLE
AttributeError: 'module' object has no attribute 'cupy'

### ISSUE THREAD

**Issue by SeekPoint** [musyoku/chainer-qrnn#2]
now I knew that the what is 'cupy', but On Mac without GPU, how can I install it or run it without copy

python train.py --source-train ../../qa_new_data/_train.q1000 --target-train ../../qa_new_data/_train.a1000 --batchsize 64  --gpu-device -1
len(source_dataset_train) is 999 
len(target_dataset_train) is 999 
data	#
train	999
vocab	1447	(source)
vocab	2099	(target)
buckets 	#data	(train)
(5, 10) 	141
(10, 15) 	165
(20, 25) 	318
(40, 50) 	179
(100, 110) 	93
(200, 210) 	102
Epoch 1
Traceback (most recent call last):
  File "train.py", line 212, in <module>
    main(args)
  File "train.py", line 127, in main
    if model.xp is cuda.cupy:
AttributeError: 'module' object has no attribute 'cupy'

**Comment by musyoku** [comment]
I fixed it.
