### ISSUE TITLE
cupy.cuda.runtime.CUDARuntimeError: cudaErrorMemoryAllocation: out of memory on predict phase

### ISSUE THREAD

**Issue by SeekPoint** [musyoku/chainer-qrnn#3]
>source:  报 读 潮 汕 职 业 技 术 学 院 的 收 费 怎 么 样 ？
 target:  汕 头 市 美 宝 化 妆 品 有 限 公 司 京 明 温 泉 度 假 村 有 限 公 司 深 圳 市 夏 尔 科 技 有 限 公 司 广 东 艺 通 装 饰 工 程 有 限 公 司 广 东 碧 桂 园 物 业 管 理 有 限 公 司 广 东 圣 都 模 具 股 份 有 限 公 司 广 州 珠 江 黄 埔 大 桥 . . .
 predict: 的
>source:  h t c 的 手 机 , 安 卓 系 统 哪 个 版 本 的 好 ? 有 什 么 不 同 吗 . 版 . . .
 target:  版 本 重 在 稳 定 吧 。 其 实 各 个 版 本 变 动 不 是 很 大 。 我 现 在 是 2 . 3 . 5 . 感 觉 就 挺 还 ， 其 实 如 果 不 是 很 必 要 不 用 刷 系 统 。 如 果 你 想 刷 手 机 可 以 的 话 可 以 找 个 安 卓 4 . 0 刷 入 。 前 提 是 手 机 要 带 队 的 起 来 。 h t c 的 s e n c e 也 可 以 升 级 的 。
 predict: 亲 的 亲
Traceback (most recent call last):
  File "cupy/cuda/memory.pyx", line 362, in cupy.cuda.memory.SingleDeviceMemoryPool.malloc (cupy/cuda/memory.cpp:7328)
  File "cupy/cuda/memory.pyx", line 263, in cupy.cuda.memory._malloc (cupy/cuda/memory.cpp:6020)
  File "cupy/cuda/memory.pyx", line 264, in cupy.cuda.memory._malloc (cupy/cuda/memory.cpp:5941)
  File "cupy/cuda/memory.pyx", line 35, in cupy.cuda.memory.Memory.__init__ (cupy/cuda/memory.cpp:1775)
  File "cupy/cuda/runtime.pyx", line 207, in cupy.cuda.runtime.malloc (cupy/cuda/runtime.cpp:3429)
  File "cupy/cuda/runtime.pyx", line 130, in cupy.cuda.runtime.check_status (cupy/cuda/runtime.cpp:2241)
cupy.cuda.runtime.CUDARuntimeError: cudaErrorMemoryAllocation: out of memory

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "cupy/cuda/memory.pyx", line 368, in cupy.cuda.memory.SingleDeviceMemoryPool.malloc (cupy/cuda/memory.cpp:7503)
  File "cupy/cuda/memory.pyx", line 263, in cupy.cuda.memory._malloc (cupy/cuda/memory.cpp:6020)
  File "cupy/cuda/memory.pyx", line 264, in cupy.cuda.memory._malloc (cupy/cuda/memory.cpp:5941)
  File "cupy/cuda/memory.pyx", line 35, in cupy.cuda.memory.Memory.__init__ (cupy/cuda/memory.cpp:1775)
  File "cupy/cuda/runtime.pyx", line 207, in cupy.cuda.runtime.malloc (cupy/cuda/runtime.cpp:3429)
  File "cupy/cuda/runtime.pyx", line 130, in cupy.cuda.runtime.check_status (cupy/cuda/runtime.cpp:2241)
cupy.cuda.runtime.CUDARuntimeError: cudaErrorMemoryAllocation: out of memory

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "train.py", line 212, in <module>
    main(args)
  File "train.py", line 174, in main
    print("done in {} min, lr = {}, total {} min".format(int(elapsed_time), get_current_learning_rate(optimizer), int(total_time)))
  File "/usr/lib/python3.5/contextlib.py", line 77, in __exit__
    self.gen.throw(type, value, traceback)
  File "/usr/local/lib/python3.5/dist-packages/chainer/configuration.py", line 125, in using_config
    yield
  File "train.py", line 170, in main
    dump_random_source_target_translation(model, source_buckets_train, target_buckets_train, vocab_inv_source, vocab_inv_target, num_translate=5, beam_width=1)
  File "/home/mldl/ub16_prj/chainer-qrnn/seq2seq/translate.py", line 360, in dump_random_source_target_translation
    translation_batch = translate_greedy(model, source_batch, target_batch.shape[1] * 2, len(vocab_inv_target), beam_width)
  File "/home/mldl/ub16_prj/chainer-qrnn/seq2seq/translate.py", line 70, in translate_greedy
    u = model.decode_one_step(x, encoder_last_hidden_states)
  File "/home/mldl/ub16_prj/chainer-qrnn/seq2seq/model.py", line 238, in decode_one_step
    out_data = self._forward_decoder_layer_one_step(layer_index, sum(in_data) if self.densely_connected else in_data[-1], encoder_last_hidden_states[layer_index])
  File "/home/mldl/ub16_prj/chainer-qrnn/seq2seq/model.py", line 217, in _forward_decoder_layer_one_step
    out_data = decoder.forward_one_step(in_data, encoder_last_hidden_states)
  File "../qrnn.py", line 179, in forward_one_step
    WX = self.W(X)[..., -pad-1, None]
  File "/usr/local/lib/python3.5/dist-packages/chainer/links/connection/convolution_nd.py", line 84, in __call__
    x, self.W, self.b, self.stride, self.pad, cover_all=self.cover_all)
  File "/usr/local/lib/python3.5/dist-packages/chainer/functions/connection/convolution_nd.py", line 438, in convolution_nd
    return func(x, W, b)
  File "/usr/local/lib/python3.5/dist-packages/chainer/function.py", line 200, in __call__
    outputs = self.forward(in_data)
  File "/usr/local/lib/python3.5/dist-packages/chainer/functions/connection/convolution_nd.py", line 177, in forward
    return self._forward_xp(x, W, b, cuda.cupy)
  File "/usr/local/lib/python3.5/dist-packages/chainer/functions/connection/convolution_nd.py", line 81, in _forward_xp
    y = xp.tensordot(self.col, W, (axes, axes)).astype(x.dtype, copy=False)
  File "/usr/local/lib/python3.5/dist-packages/cupy/linalg/product.py", line 193, in tensordot
    return core.tensordot_core(a, b, None, n, m, k, ret_shape)
  File "cupy/core/core.pyx", line 3206, in cupy.core.core.tensordot_core (cupy/core/core.cpp:80257)
  File "cupy/core/core.pyx", line 3242, in cupy.core.core.tensordot_core (cupy/core/core.cpp:79283)
  File "cupy/core/core.pyx", line 82, in cupy.core.core.ndarray.__init__ (cupy/core/core.cpp:6389)
  File "cupy/cuda/memory.pyx", line 283, in cupy.cuda.memory.alloc (cupy/cuda/memory.cpp:6078)
  File "cupy/cuda/memory.pyx", line 436, in cupy.cuda.memory.MemoryPool.malloc (cupy/cuda/memory.cpp:9314)
  File "cupy/cuda/memory.pyx", line 452, in cupy.cuda.memory.MemoryPool.malloc (cupy/cuda/memory.cpp:9220)
  File "cupy/cuda/memory.pyx", line 347, in cupy.cuda.memory.SingleDeviceMemoryPool.malloc (cupy/cuda/memory.cpp:7907)
  File "cupy/cuda/memory.pyx", line 373, in cupy.cuda.memory.SingleDeviceMemoryPool.malloc (cupy/cuda/memory.cpp:7682)
  File "cupy/cuda/memory.pyx", line 263, in cupy.cuda.memory._malloc (cupy/cuda/memory.cpp:6020)
  File "cupy/cuda/memory.pyx", line 264, in cupy.cuda.memory._malloc (cupy/cuda/memory.cpp:5941)
  File "cupy/cuda/memory.pyx", line 35, in cupy.cuda.memory.Memory.__init__ (cupy/cuda/memory.cpp:1775)
  File "cupy/cuda/runtime.pyx", line 207, in cupy.cuda.runtime.malloc (cupy/cuda/runtime.cpp:3429)
  File "cupy/cuda/runtime.pyx", line 130, in cupy.cuda.runtime.check_status (cupy/cuda/runtime.cpp:2241)
cupy.cuda.runtime.CUDARuntimeError: cudaErrorMemoryAllocation: out of memory
mldl@mldlUB1604:~/ub16_prj/chainer-qrnn/seq2seq$

**Comment by musyoku** [comment]
What is the size of your GPU memory?
Also tell me the version of Chainer you are using.

**Comment by SeekPoint** [comment]
gtx950m 4G

chainer 2.0.2

**Comment by musyoku** [comment]
Try turning off all logs.

```
# with chainer.using_config("train", False):
# 	if epoch % args.interval == 0:
# 		printb("translate (train)")
# 		dump_random_source_target_translation(model, source_buckets_train, target_buckets_train, vocab_inv_source, vocab_inv_target, num_translate=5, beam_width=1)

# 		if source_buckets_dev is not None:
# 			printb("translate (dev)")
# 			dump_random_source_target_translation(model, source_buckets_dev, target_buckets_dev, vocab_inv_source, vocab_inv_target, num_translate=5, beam_width=1)

# 		if source_buckets_dev is not None:
# 			printb("WER (dev)")
# 			wer_dev = compute_error_rate_buckets(model, source_buckets_dev, target_buckets_dev, len(vocab_inv_target), beam_width=1)
# 			print(mean(wer_dev), wer_dev)

elapsed_time = (time.time() - start_time) / 60.
total_time += elapsed_time
print("done in {} min, lr = {:.4f}, total {} min".format(int(elapsed_time), get_current_learning_rate(optimizer), int(total_time)))
```
